
name: Build XCFrameworks

on:
  workflow_dispatch:
    inputs:
      occt-tag:
        type: string
        description: 'The branch, tag or SHA of the OCCT repo to checkout.'
      debug-build:
        type: boolean
        default: false
      build-macos:
        type: boolean
        default: true
      build-ios:
        type: boolean
        default: true

jobs:
  build-ios:
    if: ${{ inputs.build-ios }}
    uses: flipper0l/OCCT-SPM/.github/workflows/build-framework.yaml@main
    with:
      occt-tag: ${{ inputs.occt-tag }}
      debug-build: ${{ inputs.debug-build }}
      build-ios: true
      build-macos: false

  build-macos:
    if: ${{ inputs.build-macos }}
    uses: flipper0l/OCCT-SPM/.github/workflows/build-framework.yaml@main
    with:
      occt-tag: ${{ inputs.occt-tag }}
      debug-build: ${{ inputs.debug-build }}
      build-ios: false
      build-macos: true
